### ISSUE TITLE
[GUM] BUG | Code Generation for Component doesn't include base class

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#212]
When I create a component in gum.exe (2024.8.20.0) or (9ba089d901a31a2568918263d8a81b127741bed0) and then create a component, and I want to copy the code for it, it's missing the base class so I get errors on things like:

this.SetContainedObject
this.Height
this.Width
this.Children

Steps to reproduce:
1. Open **Gum.exe**
2. Create a **new project**, **save the project**
3. Right-click **Components** and chose **Add Component**
4. Name the component anything you wish
5. Add a child item to the component (a ColoredRectangle)
6. Click on the new component
7. Under the Code tab under the editor, checkmark Show CodeGen Preview
8. Notice that the public partial class has no base class.
9. Copy this code into a C# project that contains the Gum nuget package
10. Notice you get an error on this.SetContainedObject and this.Children

I was working on trying to pull in the Button example component code into Monogame so I could test it out and found this.

Resolution:
Errors go away if I make the base class "ContainerRuntime" which I got from the Monogame.Extended documentation on GUM.  It may not be the correct way but it seems to eliminate the errors so I'm not sure if perhaps I did something wrong.

![image](https://github.com/user-attachments/assets/ea747848-cd0c-45c1-acf7-4875577cedda)

![image](https://github.com/user-attachments/assets/e0104e46-0afd-46fb-998c-16e2a3ea33d3)

**Comment by vchelaru** [comment]
Fixed by c981145a0a2ea8eece0373ce6b8a3c767ecc262c

**Comment by kaltinril** [comment]
@vchelaru unless you just didn't include this fix in your October release, this isn't resolved it doesn't appear.

![image](https://github.com/user-attachments/assets/c9850e3a-8ba5-4605-8746-82d80f5e7f4e)
![image](https://github.com/user-attachments/assets/3396d0b8-f669-454d-96c3-6a5ed33a8773)

**Comment by kaltinril** [comment]
Looks like perhaps there is a lot of things I don't understand.

I changed it to Monogame (I see you added that in your code).

It still didn't change much.

I then changed Inheritance Location (Whatever that means) to "In Generated Code" and it added `:BindableGraphicalUiElement`

However, that base class doesn't seem to exist.  Is this a "FORMS" base class?  I shouldn't need Forms or SKIA or anything just to have GUM right?

**Comment by vchelaru** [comment]
Thank you for the feedback. I'll answer these questions all in the docs, link the docs back here.

**Comment by vchelaru** [comment]
I have added subsections to the Code Tab page which should answer all of these questions:

https://docs.flatredball.com/gum/code-tab
