### ISSUE TITLE
BUG: RIght-click menu should not have the previously selected objects context menu options

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#369]
If you select something in the main treeview, then right-click on a different thing, the context menu applies to the originally selected thing.  You have to LEFT CLICK first to select it, and THEN you can right-click to get the correct context menu.

Steps to reproduce:
1. Create a component
2. Create a behavior
3. Click on the component
4. Right-click on the behavior
5. Context menu is for the component.

https://github.com/user-attachments/assets/c67e8429-daf9-41f7-afe8-753715648102

**Comment by kaltinril** [comment]
https://github.com/user-attachments/assets/323e471e-6a4e-4808-ae4a-4be5d994e6f6

**Comment by vchelaru** [comment]
fixed

**Comment by kaltinril** [comment]
Issues remain, but already opened #374 for the remaining issues
