### ISSUE TITLE
TextBox should attempt to convert input strings to common numeric types

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#609]
If you bind a TextBox to a numeric property on a ViewModel, it will successfully convert the numeric property to a string and display it in the TextBox. However, if you attempt to change the number in the textbox, it will blow up because it does not convert back to a numeric type from the input string.

While the user can fix this fairly easily with a conversion property in the ViewModel, I think they should not have to clutter the ViewModel with conversion properties for this common scenario. There is also the precedent that other forms controls can do conversions - specifically the Slider object can convert to a variety of common numeric types including `float`, `double`, `int`,  `byte`, and possibly others.

**Recommended Feature:**
The TextBox forms control should be able to convert user string input into these types:

- `decimal`
- `double`
- `float`
- `int`
- `byte`

Note that this feature lack was produced in my TerraScriber project and this is logged as a bug in my roadmap here:
https://trello.com/c/A3R4H0wr/129-typing-values-into-item-coordinates-should-not-throw-a-string-conversion-error

**Comment by vchelaru** [comment]
Fixed by 98dbd56b373694ed600f61d96ad3aa9d14d3befb

**Comment by profexorgeek** [comment]
In my test, this is not fixed. In my TerraScriber project I have a textbox bound to an `int` property on a ViewModel. If I try to enter an "8", which should have no parsing problems, it blows up. Gif:

![Image](https://github.com/user-attachments/assets/3053e9de-8011-44ca-85f9-bb61b73ec280)

**Comment by profexorgeek** [comment]
Reopening issue for discussion...

**Comment by vchelaru** [comment]
This issue ultimately is being addressed by adding support for UpdateSourceTrigger. Assigning to @vicdotexe
